### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by xyzfrozen** [krn1pnc/krn1pnc.github.io#1]
能不能看看 MX 13联测 第四场 T2 的代码，有点没看懂官方的题解，也没有std，想看看您的代码

找了好久都没找到您的联系方式，只能在这里问了，如果打扰到您了抱歉

**Comment by krn1pnc** [comment]
这题其实是 [原](https://www.luogu.com.cn/problem/P4785)，我的代码可以见 [这里](https://loj.ac/s/1948749)．

**Comment by xyzfrozen** [comment]
> 这题其实是 [原](https://www.luogu.com.cn/problem/P4785)，我的代码可以见 [这里](https://loj.ac/s/1948749)．

万分感谢！

可不可以加下 dalao qq，好多联测题目都找不到官方 tj 以外的，希望可以跟 dalao交流一下，我也是 HB oier
